make:
	g++ -w *.cpp \
	../../lib/Box2D/Collision/*.cpp \
	../../lib/Box2D/Collision/Shapes/*.cpp \
	../../lib/Box2D/Common/*.cpp \
	../../lib/Box2D/Dynamics/*.cpp \
	../../lib/Box2D/Dynamics/Contacts/*.cpp \
	../../lib/Box2D/Dynamics/Joints/*.cpp \
    -I ../../lib \
	-I ../../lib/Box2D \
    -lsfml-graphics -lsfml-window -lsfml-system
